version: '3.3'
services:
    nginx:
      image: nginx:latest
      depends_on:
      - user
      - client
      volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - {target: 80, published: 80, protocol: tcp}
    client:
      depends_on:
      - user
      image: eyjafjalla/skyre-client:latest
      ports:
      - {target: 3000, published: 3000, protocol: tcp}
    user:
      depends_on:
      - mysql
      image: eyjafjalla/skyre-user:latest
      ports:
      - {target: 9003, published: 9003, protocol: tcp}
    core:
      image: eyjafjalla/skyre-core:latest
      ports:
      - {target: 9001, published: 9001, protocol: tcp}
    anpr:
      image: eyjafjalla/skyre-anpr:latest
      ports:
      - {target: 8082, published: 8082, protocol: tcp}
    citizen:
      image: eyjafjalla/skyre-citizen:latest
      ports:
      - {target: 8081, published: 8081, protocol: tcp}
    finance:
      image: eyjafjalla/skyre-finance:latest
      ports:
      - {target: 8083, published: 8083, protocol: tcp}
    mobile:
      image: eyjafjalla/skyre-mobile:latest
      ports:
      - {target: 8084, published: 8084, protocol: tcp}
    case:
      image: eyjafjalla/skyre-case:latest
      ports:
      - {target: 8005, published: 8005, protocol: tcp}
    audit-consumer:
      depends_on:
      - active-mq
      image: eyjafjalla/skyre-audit-consumer:latest
      ports:
      - {target: 9002, published: 9002, protocol: tcp}
    mongo:
      depends_on:
      - active-mq
      image: mongo
      ports:
      - {target: 27017, published: 27017, protocol: tcp}
    active-mq:
      image: webcenter/activemq
      ports:
      - {target: 61616, published: 61616, protocol: tcp}
    mysql:
     image: mysql/mysql-server
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: example
       MYSQL_DATABASE: users
       MYSQL_USER: test
       MYSQL_PASSWORD: test1234
     ports:
     - {target: 3306, published: 3306, protocol: tcp}
