version: '3.3'
services:
    nginx:
      image: nginx
      depends_on:
      - user
      - client
      volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        protocol: tcp
        published: 80

    client:
      depends_on:
      - user
      image: eyjafjalla/skyre-client:latest
      build:
        context: ./Skyre-FrontEnd
        dockerfile: Dockerfile
      ports:
      - "3000:3000"

    user:
      depends_on:
      - mysql
      image: eyjafjalla/skyre-user:latest
      build:
        context: ./Skyre_User
        dockerfile: Dockerfile
      ports:
      - "9003:9003"

    core:
      image: eyjafjalla/skyre-core:latest
      build:
        context: ./Skyre-SpringCore
        dockerfile: Dockerfile
      ports:
      - "9001:9001"

    anpr-api:
      image: eyjafjalla/skyre-anpr:latest
      build:
        context: ./SpringANPRAPI
        dockerfile: Dockerfile
      ports:
      - "8082:8082"

    citizen-api:
      image: eyjafjalla/skyre-citizen:latest
      build:
        context: ./SpringCitizenAPI2
        dockerfile: Dockerfile
      ports:
      - "8081:8081"     
      
    finance-api:
      image: eyjafjalla/skyre-finance:latest
      build:
        context: ./SpringFinanceAPI
        dockerfile: Dockerfile
      ports:
      - "8083:8083"
    
    mobile-api:
      image: eyjafjalla/skyre-mobile:latest
      build:
        context: ./SpringMobileAPI
        dockerfile: Dockerfile
      ports:
      - "8084:8084"
    
    case:
      image: eyjafjalla/skyre-case:latest
      build:
        context: ./Skyre-Case
        dockerfile: Dockerfile
      ports:
      - "8085:8085"
    
    audit-consumer: 
      depends_on:
      - active-mq
      image: eyjafjalla/skyre-audit-consumer:latest
      build:
        context: ./Skyre-Consumer
        dockerfile: Dockerfile
      ports:
      - "9002:9002"

    mongo:
      depends_on:
      - active-mq
      image: mongo
      ports:
      - "27017:27017"

    active-mq:
      image: webcenter/activemq
      ports:
      - "61616:61616"

    mysql:
     image: mysql/mysql-server
         restart: always
     environment:
       MYSQL_ROOT_PASSWORD: example
       MYSQL_DATABASE: users
       MYSQL_USER: test
       MYSQL_PASSWORD: test1234
     ports:
     - "3306:3306"

